package ru.ruslan.spring.cad;

public enum Mode {
    DRAW_LINE,
    ZOOM,
    PANORAM,
    DRAW_CIRCLE,
    DIVIDE, DRAW_CIRCLE3DOTS, DRAW_SPLINEBEZIE, DRAW_ARCRC, DRAW_RECT, DRAW_POLYGON_IN, DRAW_RECT_CENTR, DRAW_ARC3DOTS, DRAW_SPLINE_MYSPLINE, DRAW_POLYGON_OUT
}
